import tkinter as tk
from tkinter import ttk
from tkinter import * 
from Zakat import dataNama
Orang = dataNama("",0,"",0,0,0,"",0,0)
def clear():
    stringOutputKeterangan.set("")
def SubmitHarga():
    iNama = stringNama.get()
    iUmur = stringUmur.get()
    iPekerjaan = stringPekerjaan.get()
    iEmas = stringEmas.get()
    iPenghasilan = stringPenghasilan.get()
    Orang.setData(iNama,int(iUmur),iPekerjaan,int(iPenghasilan),iEmas)
    Orang.hitung()
    stringOutputNama.set(Orang.getnama())
    stringOutputUmur.set(Orang.getumur())
    stringOutputPekerjaan.set(Orang.getpekerjaan())
    stringOutputZakat.set(Orang.getzakat())
    stringOutputNizhab.set(Orang.getnisab())
    stringOutputKeterangan.set(Orang.getketerangan())

root = Tk()

root.geometry('450x530')
root.configure(background='#8FBC8F')
root.title('Program Perhitungan Zakat')
Button(root, text='Oke', bg='#2F4F4F', font=('arial', 12, 'normal'), command=SubmitHarga).place(x=164, y=240)
stringNama = StringVar()
tInputNama=Entry(root,textvariable=stringNama).place(x=210, y=22)
stringPekerjaan = StringVar()
tInputPekerjaan=Entry(root,textvariable=stringPekerjaan).place(x=210, y=52)
stringUmur = IntVar()
tInputUmur =Entry(root,textvariable=stringUmur).place(x=210, y=82)
stringPenghasilan = StringVar()
tInputPenghasilan=Entry(root,textvariable=stringPenghasilan).place(x=275, y=153)
stringEmas = IntVar()
tInputEmas=Entry(root,textvariable=stringEmas).place(x=274, y=185)
stringOutputNama = StringVar()
tOutputNama=Entry(root,state='readonly',textvariable=stringOutputNama).place(x=274, y=320)
stringOutputUmur = StringVar()
tOutputUmur=Entry(root,state='readonly',textvariable=stringOutputUmur).place(x=274, y=348)
stringOutputPekerjaan = StringVar()
tOutputPekerjaan=Entry(root,state='readonly',textvariable=stringOutputPekerjaan).place(x=274, y=376)
stringOutputNizhab = StringVar()
tOutputNizhab=Entry(root,state='readonly',textvariable=stringOutputNizhab).place(x=274, y=416)
stringOutputZakat = StringVar()
tOutputZakat=Entry(root,state='readonly',textvariable=stringOutputZakat).place(x=274, y=447)
stringOutputKeterangan = StringVar()
tOutputKeterangan=Entry(root,state='readonly',textvariable=stringOutputKeterangan).place(x=274, y=477)
Label(root, text='Masukkan Nama Anda : ', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=21, y=18)
Label(root, text='Masukkan Pekerjaan  :', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=19, y=50)
Label(root, text='Masukkan Umur Anda :', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=19, y=82)
Label(root, text='Masukkan Penghasilan Per Bulan :', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=15, y=152)
Label(root, text='Masukkan Harga Emas : ', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=16, y=193)
Label(root, text='Data Zakat Profesi', bg='#8FBC8F', font=('arial', 18, 'normal')).place(x=90, y=279)
Label(root, text='Nama', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=22, y=320)
Label(root, text='Umur', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=21, y=348)
Label(root, text='Pekerjaan', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=20, y=375)
Label(root, text='Nizhab', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=21, y=416)
Label(root, text='Zakat yang dikeluarkan', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=21, y=447)
Label(root, text='Keterangan', bg='#8FBC8F', font=('arial', 12, 'normal')).place(x=21, y=477)
root.mainloop()
